services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'cultureamp/trufflehog']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
