name: TruffleHog Secret Scanner
description: Scans for secrets in the container image.
author: https://github.com/liamstevens
requirements: []
configuration:
  properties:
    trufflehog-image-uri:
      type: string
      description: The URI of the TruffleHog image.
    image-uri:
      type: string
      description: The URI of the container image to scan.
  additionalProperties: false
