#!/bin/bash
set -euo pipefail

image="$BUILDKITE_PLUGIN_TRUFFLEHOG_IMAGE_URI"
echo "--- :docker: Pulling images"
docker pull trufflesecurity/trufflehog:latest
echo "--- :docker: Running TruffleHog"
results="$(docker run --rm -it -v '$PWD:/pwd' trufflesecurity/trufflehog:latest docker --image=${image} --json --only-verified --fail)"
trufflehog_status=$?
files = $(echo $results | jq '. | .SourceMetadata.Data.Docker.file')

# If any findings, annotate the build.
if [[ $trufflehog_status -ne 0 ]]; then 
    buildkite-agent annotate --style 'error' "Trufflehog found secrets in the container image:\n $files"
else
    buildkite-agent annotate --style 'success' "No secrets detected by TruffleHog."
fi
