#!/bin/bash
set -euo pipefail

temp_results="/tmp/results.json"
touch $temp_results
echo "--- :docker: Pulling images"
docker pull "${BUILDKITE_PLUGIN_TRUFFLEHOG_TRUFFLEHOG_IMAGE_URI}"
echo "--- :docker: Running TruffleHog"
docker run --rm -it -v "$PWD:/pwd" "${BUILDKITE_PLUGIN_TRUFFLEHOG_TRUFFLEHOG_IMAGE_URI}" docker --image="${BUILDKITE_PLUGIN_TRUFFLEHOG_IMAGE_URI}" --json --only-verified | tee "${temp_results}"
echo "--- :docker: Parsing results"
files="$(cat $temp_results | jq '. | .SourceMetadata.Data.Docker.file')"
files_status=$?

# If any findings, annotate the build.
if [[ $files_status -eq 0 ]]; then 
    buildkite-agent annotate --style 'error' "Trufflehog found secrets in the container image:\n $files"
    exit 1
else
    buildkite-agent annotate --style 'success' "No secrets detected by TruffleHog."
    exit 0
fi
